### ISSUE TITLE
Steps Needed to make the Generator Work in a new project

### ISSUE THREAD

**Issue by justwiebe** [RoleModel/rolemodel_rails#106]
1. Verify you're using rails v7
2. `rails new <app> -j=webpack -c=sass -d=postgresql -T`
3. `cd <app>`
4. `bundle add bcrypt`
5. Add generator to Gemfile
6. `bundle`
7. Run the generator(s)
8. `bin/setup`
9. Start the server

**Comment by BakoviDagi** [comment]
Found some more things needed:

- update `ecmaVersioin` to `latest` in `.eslintrc.cjs`
- Fix eslint errors
- Replace semaphore `webpacker` lines with the webpack config from `engage-learn`
- Add the following gems:
  -  `bundler-audit`
  - `rspec_junit_formatter`
- Run `bundle install --binstubs`
