### ISSUE TITLE
TurboFrameLinkHelper#modal_link_to has unexpectedly broken signatures

### ISSUE THREAD

**Issue by reedrolemodel** [RoleModel/rolemodel_rails#109]
`link_to` supports the following signatures:
```ruby
link_to(body, url, html_options = {})
  # url is a String; you can use URL helpers like
  # posts_path

link_to(body, url_options = {}, html_options = {})
  # url_options, except :method, is passed to url_for

link_to(options = {}, html_options = {}) do
  # name
end

link_to(url, html_options = {}) do
  # name
end

link_to(active_record_model)
```
If you call [`modal_link_to`](https://github.com/RoleModel/rolemodel_rails/blob/master/lib/generators/rolemodel/modals/templates/app/helpers/turbo_frame_link_helper.rb#L6) with an url and a block (signature 4 above) you get `wrong number of arguments (given 1, expected 2..3)`. If you pass `name` to satisfy the required number of args, it errors with `undefined method 'merge' for "/clients/1/edit":String`. It seems like `modal_link_to` should work like `link_to` or at least support signature 4 with optional `html_options`.

**Comment by OutlawAndy** [comment]
Thanks @reedrolemodel.  Anyway you could confirm that PR #110 resolves this for you?

**Comment by reedrolemodel** [comment]
It was hard to tell without a test so I added one [here](https://github.com/RoleModel/rolemodel_rails/blob/reed/bugfix-modal-link-to/example_rails7/spec/helpers/turbo_frame_link_helper_spec.rb). If that test looks good maybe it can be added to the generator. The test confirms your fix is good. Thanks!

**Comment by OutlawAndy** [comment]
@reedrolemodel I saw your comment only after merging the PR.  Thank you for writing that test.  If you want to open a PR with branch, I'll approve it.
